version: '3.9'

services:
  ml-env-jupyter:
    container_name: ml-env-jupyter
    build: ./
    ports: 
        - 8888:8888
    volumes: 
        - "./:/work"
  ml-env-jetbrains:
    container_name: ml-env-jetbrains
    image: registry.jetbrains.team/p/prj/containers/projector-pycharm-p:latest
    ports:
      - 8887:8887
    environment:
      - PROJECTOR_USER_NAME=work
    volumes:
      - "./:/home/work"

  