version: '3.9'

services:
  ml-env-jupyter:
    container_name: ml-env-jupyter
    build: ..
    ports: 
        - "8889:8888"
    volumes: 
        - "./:/work"
    environment:
      - JUPYTER_TOKEN=0000
      - JUPYTER_PASS=0000
#  ml-env-jetbrains:
#    container_name: ml-env-jetbrains
#    image: registry.jetbrains.team/p/prj/containers/projector-pycharm-p:latest
#    ports:
#      - 8887:8887
#    environment:
#      - PROJECTOR_USER_NAME=work
#    volumes:
#      - "./:/home/work"

  