wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.10
    framework: xgboost
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.9.9
    session_history: code/_session_history.ipynb
    start_time: 1645390399
    t:
      1:
      - 5
      - 6
      2:
      - 5
      - 6
      3:
      - 2
      - 16
      4: 3.9.9
      5: 0.12.10
      8:
      - 1
      - 5
wandb_nb:
  desc: null
  value: wandb_credit_soc
